on:
    push:
        branches: [main]

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest

        steps:
            -   name: Check out Go Code
                uses: actions/checkout@v4

            -   name: Set up Go
                uses: actions/setup-go@v5

            -   name: Build the Application
                run: scripts/buildprod.sh

